server:
  port: 8080

spring:
  application:
    name: Kanbaniser
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kanbaniserdb?createDatabaseIfNotExist=true&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

kanbaniser:
  app:
    jwtCookieName: kanbaniserauthcookie
    jwtSecret: ==============================================test==============================================
    jwtExpirationMs: 86400000